extends: eslint:recommended
parserOptions:
  ecmaVersion: 2017
plugins:
  - import
env:
    commonjs: true
    browser: true
    mocha: true
    es6: true
rules:
    no-undefined: error
    no-var: error
    indent:
      - warn
      - 4
    no-unused-vars: error
    require-jsdoc:
      - warn
      - require:
          FunctionDeclaration: true
          ClassDeclaration: true
          MethodDefinition: true
          ArrowFunctionExpression: true
          FunctionExpression: true
    valid-jsdoc:
      - warn
      - requireParamDescription: false
        requireReturnDescription: false
