language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo build --verbose --features serde_support
  - cargo test --verbose
  - cargo test --verbose --features serde_support
