version: 2.1
jobs:
  test:
    docker:
      - image: "cimg/ruby:<< parameters.ruby_version >>"
      - image: cimg/redis:6.2.6
      - image: memcached:1.6.18
    working_directory: ~/sdk
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install --jobs=4 --retry=3
      - run:
          name: Run tests
          command: bundle exec rake
  publish:
    docker:
      - image: cimg/ruby:3.2.0
    steps:
      - checkout
      - run:
          name: Publish to Rubygems
          command: bundle exec rake release
workflows:
  version: 2
  test-and-publish:
    jobs:
      - test:
          matrix:
            parameters:
              ruby_version: ["3.2", "3.1", "3.0", "2.7", "2.6"]
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
