version: 2.1
executors:
  sonar-scanner:
    docker:
      - image: sonarsource/sonar-scanner-cli:4.7.0
jobs:
  test-ruby:
    parameters:
      ruby_version:
        type: string
    docker:
      - image: "cimg/ruby:<< parameters.ruby_version >>"
      - image: cimg/redis:6.2.6
      - image: memcached:1.6.18
    working_directory: ~/sdk
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Run tests
          command: COVERAGE=true bundle exec rake
      - run:
          name: Display content
          command: ls -al
      - persist_to_workspace:
          root: .
          paths:
            - .
  publish:
    docker:
      - image: cimg/ruby:3.2.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Publish to Rubygems
          command: bundle exec rake release
  sonarqube_analysis:
    working_directory: ~/sdk
    executor: sonar-scanner
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute sonar-scanner
          command: sonar-scanner -Dsonar.host.url=$SONARQUBE_HOST -Dsonar.login=$SONARQUBE_OPS_CI_TOKEN -Dsonar.buildString=$CIRCLE_SHA1 -Dsonar.analysis.build.url=$CIRCLE_BUILD_URL
workflows:
  test-and-publish:
    jobs:
      - test-ruby:
          matrix:
            parameters:
              ruby_version: ["3.2", "3.1", "3.0", "2.7"]
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - test-ruby
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - sonarqube_analysis:
          context: procore-sonarqube-ci
          requires:
            - test-ruby-3.2
          #filters:
          #  branches:
          #    only:
          #      - master
