[package]
name = "weaver_common"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
paris = { version = "1.5.15", features = ["macros"] }
tinytemplate = "1.1"
miette = { version = "7.2.0", features = ["fancy"] }
thiserror.workspace = true

serde.workspace = true
serde_json.workspace = true

