[package]
name = "weaver_forge"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true

[dependencies]
minijinja = { version = "1.0.12", features = ["loader"] }
thread_local = "1.1.7"
convert_case = "0.6.0"

thiserror.workspace = true
serde.workspace = true
serde_yaml.workspace = true