openapi: 3.0.1
info:
  title: Semantic Kernel Plugin
  description: A plugin that allows the user to call Semantic Kernel Functions.
  version: 'v1'
servers:
  - url: http://localhost:5000
paths:
  /skills/{skill_name}/functions/{function_name}:
    post:
      operationId: executeFunction
      summary: Execute the requested semantic function
      parameters:
      - in: path
        name: skill_name
        schema:
          type: string
        required: true
        description: The name of the semantic skill.
      - in: path
        name: function_name
        schema:
          type: string
        required: true
        description: The name of the semantic function within the skill
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/executeFunctionRequest'
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    executeFunctionRequest:
      type: object
      properties:
        input:
          type: string
      required:
        - input
      additionalProperties: true