---
name: Release Please

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Process Release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4.0.2
        id: release

    outputs:
      paths_released: ${{ steps.release.outputs.paths_released }}

  publish:
    needs: release
    name: Publish Gems
    runs-on: ubuntu-latest
    if: ${{ needs.release.outputs.paths_released != '[]'}}

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        path: ${{ fromJson(needs.release.outputs.paths_released) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
      - name: Configure RubyGems
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_API_KEY}}"

        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials

      - uses: ruby/setup-ruby@v1.165.1
        with:
          ruby-version: "3.0"
          bundler: latest
          bundler-cache: false
          working-directory: ${{ matrix.path }}

      - name: Publish to RubyGems
        working-directory: ${{ matrix.path }}
        run: |
          bundle exec rake --trace build
          bundle exec rake --trace release:rubygem_push
