# Copyright 2023 Google LLC
#
# This is “Software” that is licensed under the “General Software” section of
# the Service Specific Terms (https://cloud.google.com/terms/service-terms) for
# usage in accordance with the following “Scope of Use”: This file may only be
# used on an Anthos cluster, including any associated ci/cd use. “Anthos
# cluster” is defined as “A Cluster (of any kind) registered to a fleet project
# where the Anthos API is enabled”.
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AsmPeerAuthnStrictMtls
metadata:
  name: pci-dss-v3.2.1-asm-peer-authn-strict-mtls
  labels:
    policycontroller.gke.io/bundleName: pci-dss-v3.2.1
  annotations:
    policycontroller.gke.io/bundleVersion: "202312.0"
    policycontroller.gke.io/constraintData: |-
      "{
        bundleName: 'pci-dss-v3.2.1',
        bundleDisplayName: 'PCI DSS v3.2.1',
        bundleLink: 'https://cloud.google.com/anthos-config-management/docs/how-to/using-pci-dss-v3',
        bundleVersion: '202312.0',
        bundleDescription: 'Use the PCI DSS v3.2.1 policy bundle with Policy Controller to evaluate the compliance of your cluster resources against some aspects of the Payment Card Industry (PCI) Data Security Standard (DSS) v3.2.1.',
        controlNumbers: '[4.1]',
        severity: 'UNSPECIFIED',
        description: 'Ensures PeerAuthentications cannot overwrite strict mTLS.',
        remediation: 'Cannot use PeerAuthentications other than strict mTLS. Use strict mTLS. See "Mutual TLS" for more information: https://istio.io/latest/docs/ops/best-practices/security/#mutual-tls',
        minimumTemplateLibraryVersion: '1.11.1',
        constraintHash: '3fc99dbf61bc7c0f9c4192e0eb50ca923727d63d9e7dd6d088cb9327fe93e0e9'
      }"
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups:
          - security.istio.io
        kinds:
          - PeerAuthentication
  parameters:
    strictnessLevel: High
